name: graspPlugin Builder

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  orig-melodic:
    name: graspPlugin(original, melodic)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cnoid_tag: ["v1.7.0", "v1.6.0", "v1.5.0"]
    container:
      image: ghcr.io/kazuki0824/hlab-nxo-setup:melodic
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
      - name: Fetch graspPlugin from original gitlab
        run: git clone http://${{ secrets.GRASPPLUGIN_CRED_USER }}:${{ secrets.GRASPPLUGIN_CRED_PASS }}@spica.ms.t.kanazawa-u.ac.jp/gitlab/tsuji/grasp-plugin.git --depth 1
      - name: Execute setup_choreonoid.sh
        run: ./setup_choreonoid.sh ${{ matrix.cnoid_tag }}

  orig-kinetic:
    name: graspPlugin(original, kinetic)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cnoid_tag: ["v1.7.0", "v1.6.0", "v1.5.0"]
    container:
      image: ghcr.io/kazuki0824/hlab-nxo-setup:kinetic
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
      - name: Fetch graspPlugin from original gitlab
        run: git clone http://${{ secrets.GRASPPLUGIN_CRED_USER }}:${{ secrets.GRASPPLUGIN_CRED_PASS }}@spica.ms.t.kanazawa-u.ac.jp/gitlab/tsuji/grasp-plugin.git --depth 1
      - name: Execute setup_choreonoid.sh
        run: ./setup_choreonoid.sh ${{ matrix.cnoid_tag }}
